apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: MLMicroservice
  region: us-east-1

vpc:
  id: vpc-0ecbf2edb7350f107
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-08c1fd9f026971198
      us-east-1b:
        id: subnet-0c2b23475edfd09a1
    private:
      us-east-1a:
        id: subnet-0a51e475748045f82
      us-east-1b:
        id: subnet-082f6b73cbacef3b3

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
