apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    microservice: python-sklearn-ml
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 80
