# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "./requirements.txt" }}
      
      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  
  register_image:
    docker:
      - image: python:3.9.0-alpine
    
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            apk add --update docker-cli
            pip3 install --upgrade pip
            pip3 install awscli
            aws --version
      
      - setup_remote_docker:
          version: 20.10.14
      
      - run:
          name: authenticate docker client
          command: |
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 284052999278.dkr.ecr.us-east-1.amazonaws.com
      
      - run:
          name: build docker image
          command: |
            docker build -t ml-microservice-udacity-capstone .
      
      - run:
          name: tag docker image
          command: |
            docker tag ml-microservice-udacity-capstone:latest 284052999278.dkr.ecr.us-east-1.amazonaws.com/ml-microservice-udacity-capstone:latest
      
      - run:
          name: push docker image
          command: |
            docker push 284052999278.dkr.ecr.us-east-1.amazonaws.com/ml-microservice-udacity-capstone:latest
  
  set_kubeconfig:
    docker:
      - image: circleci/node:13.8.0
    
    steps:
      - checkout
      
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl less
            sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl
            unzip awscliv2.zip
            sudo ./aws/install
      
      # - setup_remote_docker:
      #     version: 20.10.14
      
      # - run:
      #     name: Current kubeconfig
      #     command: cat ~/.kube/config
      
      # - run:
      #     name: Remove current kubeconfig
      #     command: rm ~/.kube/config
      
      - run:
          name: Set new kubeconfig
          command: aws eks --region us-east-1 update-kubeconfig --name MLMicroservice
      
      - run:
          name: Test new kubeconfig
          command: kubectl get svc

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  ml-microservice-workflow:
    jobs:
      - build
      - set_kubeconfig
      - register_image:
          requires: [build]
